# Generated by Django 5.1.4 on 2025-05-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creared_date',
            new_name='created_date',
        ),
    ]
